ALTER TABLE public.caixa
  ADD COLUMN IF NOT EXISTS origem TEXT,
  ADD COLUMN IF NOT EXISTS categoria TEXT,
  ADD COLUMN IF NOT EXISTS forma_pagamento TEXT,
  ADD COLUMN IF NOT EXISTS produto_id UUID REFERENCES public.produtos(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS produto_nome TEXT,
  ADD COLUMN IF NOT EXISTS quantidade INTEGER,
  ADD COLUMN IF NOT EXISTS taxa_percentual NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS valor_bruto NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS valor_taxa NUMERIC(10,2);

ALTER TABLE public.vendas
  ADD COLUMN IF NOT EXISTS forma_pagamento TEXT,
  ADD COLUMN IF NOT EXISTS taxa_percentual NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS valor_taxa NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS valor_liquido NUMERIC(10,2);
